repro script to proof that at least 2020.11.4 and also 2020.8.13 has this issue

diff --git a/reproduce_bug b/reproduce_bug
--- a/reproduce_bug
+++ b/reproduce_bug
@@ -1,6 +1,16 @@
 #!/bin/bash
-# We are currently using: 2020.8.13
-# Latest at 2020-11-10: 2020.11.4
+# We are currently using pipenv version: 2020.8.13
+# Latest version at time of writing: 2020.11.4
 
-docker build --build-arg PIPENV_VERSION=2020.8.13 -t pipenv-graph-bug .
+set -e
+
+# TEST_PIPENV_VERSION=2020.8.13
+TEST_PIPENV_VERSION=2020.11.4
+
+echo "Running repro against pipenv version: ${TEST_PIPENV_VERSION}"
+
+docker build --build-arg TEST_PIPENV_VERSION=$TEST_PIPENV_VERSION -t pipenv-graph-bug .
+
+echo "About to run docker run... it can take a minute before output appears.. just hang on!"
+
 docker run --rm pipenv-graph-bug
